spring:
  application:
    name: msk-saslscram-auth
  config:
    import:
      - "aws-parameterstore:/config/application/"

logging:
  level:
    root: info
    io.awspring.cloud: debug

kafka-topics:
  common-settings:
    default-partitions: 2
    default-replicas: 2
  topics:
    english-greetings: greetings.english
    multilingual-greetings: greetings.multilingual
